const DOM = {
  container: document.getElementById('game-container'),
  titleScreen: document.getElementById('title-screen'),
  mapScreen: document.getElementById('map-screen'),
  dialogueBox: document.getElementById('dialogue-box'),
  choicesLayer: document.getElementById('choices-layer'),
  endingScreen: document.getElementById('ending-screen'),
  nameTag: document.getElementById('name-tag'),
  dialogueText: document.getElementById('dialogue-text'),
  clickIndicator: document.getElementById('click-indicator'),
  bgCanvas: document.getElementById('bg-canvas'),
  charImage: document.getElementById('char-image'),
  mapContainer: document.getElementById('map-container'),
  startBtn: document.getElementById('start-btn'),
  restartBtn: document.getElementById('restart-btn'),
  endingTitle: document.getElementById('ending-title'),
  endingType: document.getElementById('ending-type'),
  endingText: document.getElementById('ending-text'),
  confirmModal: document.getElementById('confirm-modal'),
  confirmText: document.getElementById('confirm-text'),
  confirmYes: document.getElementById('confirm-yes'),
  confirmNo: document.getElementById('confirm-no'),
};
